'use client';

import React, { useState } from 'react';
import Link from 'next/link';

export default function CriarMusica() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    // Step 1
    occasion: '',
    honoreeName: '',
    relationship: '',
    // Step 2
    story: '',
    importantMoments: '',
    qualities: '',
    requiredPhrase: '',
    forbiddenSubjects: '',
    // Step 3
    musicStyle: '',
    voiceType: '',
    emotion: '',
    tempo: '',
    // Step 4
    customerName: '',
    customerEmail: '',
    customerPhone: '',
    termsAccepted: false,
    // Step 5: Approved lyrics (generated by API)
    lyrics: '',
    lyricsVersion: 1,
    lyricsStatus: 'idle', // 'idle', 'generating', 'generated', 'error'
    lyricsComment: '',
    // Step 6: Selected package
    selectedPackage: '',
    // Step 7: Addons
    addons: {
      extraSongs2: false,
      extraSongs3: false,
      photoVideo: false,
      spotifyDistribution: false,
      premiumCover: false,
      qrCode: false,
      instrumentalVersion: false,
      wavFormat: false,
      priorityDelivery: false,
    }
  });

  const totalSteps = 8;

  // Occasions list
  const occasions = [
    { id: 'aniversario', label: '🎂 Aniversário', desc: 'Homenageie alguém em seu dia especial' },
    { id: 'casamento', label: '💒 Casamento', desc: 'A trilha sonora para o grande dia' },
    { id: 'namoro', label: '💕 Namoro / Aniversário de Relação', desc: 'Eternize a história de amor' },
    { id: 'mae_pai', label: '👩‍👦 Dia das Mães / Pais', desc: 'Um obrigado especial em forma de canção' },
    { id: 'empresa', label: '🏢 Empresa / Institucional', desc: 'Fortaleça a sua marca com uma trilha exclusiva' },
    { id: 'outra', label: '✨ Outra Ocasião', desc: 'Qualquer outro momento marcante' }
  ];

  // Styles list
  const stylesList = [
    { id: 'acoustic_folk', label: 'acoustic_folk', name: '🎸 Folk Acústico', desc: 'Emocional, aconchegante e intimista' },
    { id: 'mpb_bossa', label: 'mpb_bossa', name: '☕ MPB / Bossa Nova', desc: 'Suave, clássico e sofisticado' },
    { id: 'pop_rock', label: 'pop_rock', name: '⚡ Pop Rock', desc: 'Animado, moderno e com energia' },
    { id: 'gospel', label: 'gospel', name: '⛪ Gospel / Adoração', desc: 'Emocionante, inspirador e de fé' },
    { id: 'sertanejo', label: 'sertanejo', name: '🤠 Sertanejo', desc: 'Tradicional, romântico e caloroso' },
    { id: 'samba_pagode', label: 'samba_pagode', name: '🥁 Samba / Pagode', desc: 'Descontraído, alegre e rítmico' }
  ];

  // Packages configurations
  const packagesList = [
    {
      id: 'essencial',
      name: 'Essencial',
      price: 49.90,
      desc: '1 Música + MP3 + Capa Simples'
    },
    {
      id: 'presente',
      name: 'Presente Completo',
      price: 79.90,
      desc: '1 Música + MP3/WAV + Capa Personalizada + QR Code'
    },
    {
      id: 'tres_versoes',
      name: 'Multi-Estilos (3 Versões)',
      price: 119.90,
      desc: '3 Versões com ritmos diferentes + Capa + QR Code'
    }
  ];

  // Addons configuration
  const addonsConfig = [
    { id: 'extraSongs2', name: '➕ 2 Músicas adicionais (mesma letra, estilos diferentes)', price: 39.90 },
    { id: 'extraSongs3', name: '➕ 3 Músicas adicionais (mesma letra, estilos diferentes)', price: 59.90 },
    { id: 'photoVideo', name: '🎥 Vídeo com fotos (sincronizado com a música)', price: 49.90 },
    { id: 'spotifyDistribution', name: '🎧 Publicação no Spotify e plataformas de streaming', price: 99.90 },
    { id: 'premiumCover', name: '🖼️ Capa Premium personalizada profissional', price: 19.90 },
    { id: 'qrCode', name: '📱 QR Code da música para cartões e presentes', price: 9.90 },
    { id: 'instrumentalVersion', name: '🎤 Versão Instrumental (Sem voz - para karaokê)', price: 19.90 },
    { id: 'wavFormat', name: '💿 Áudio em formato WAV (Qualidade de estúdio)', price: 9.90 },
    { id: 'priorityDelivery', name: '🚀 Entrega Prioritária em até 24 horas', price: 29.90 },
  ];

  // Price calculations
  const getSelectedPackagePrice = () => {
    const pkg = packagesList.find(p => p.id === formData.selectedPackage);
    return pkg ? pkg.price : 0;
  };

  const getAddonsPrice = () => {
    let price = 0;
    addonsConfig.forEach(addon => {
      if (formData.addons[addon.id]) {
        price += addon.price;
      }
    });
    return price;
  };

  const getTotalPrice = () => {
    return getSelectedPackagePrice() + getAddonsPrice();
  };

  // State setters
  const updateField = (name, value) => {
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const updateAddon = (id, value) => {
    setFormData(prev => ({
      ...prev,
      addons: {
        ...prev.addons,
        [id]: value
      }
    }));
  };

  // Navigation handlers
  const nextStep = () => {
    if (step === 4) {
      generateLyrics();
    }
    setStep(prev => Math.min(prev + 1, totalSteps));
  };

  const prevStep = () => {
    setStep(prev => Math.max(prev - 1, 1));
  };

  // API Call simulation for lyrics generation (Phase 3 will make it real)
  const generateLyrics = async () => {
    updateField('lyricsStatus', 'generating');
    try {
      const response = await fetch('/api/lyrics/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          occasion: formData.occasion,
          honoreeName: formData.honoreeName,
          relationship: formData.relationship,
          story: formData.story,
          importantMoments: formData.importantMoments,
          qualities: formData.qualities,
          requiredPhrase: formData.requiredPhrase,
          forbiddenSubjects: formData.forbiddenSubjects,
          musicStyle: formData.musicStyle,
          voiceType: formData.voiceType,
          emotion: formData.emotion,
        })
      });

      if (response.ok) {
        const data = await response.json();
        setFormData(prev => ({
          ...prev,
          lyrics: data.lyrics,
          lyricsStatus: 'generated'
        }));
      } else {
        throw new Error('Falha ao gerar letra');
      }
    } catch (err) {
      console.error(err);
      // Fallback preview so the UI works even if API is offline
      setFormData(prev => ({
        ...prev,
        lyrics: `[Verso 1]\nNo calor desse abraço eu encontrei meu lugar\nCom o(a) ${formData.honoreeName || 'homenageado'}, aprendi o que é amar\nDesde o início, nossa história foi escrita com emoção\nE hoje trago esse canto direto do coração.\n\n[Refrão]\nO tempo passa, mas a lembrança fica\nEssa história que a vida nos ensina e simplifica\n${formData.requiredPhrase || 'Para sempre com você'},\nNossa trilha não tem fim, e nada nos afasta.\n\n[Verso 2]\nLembro bem de cada detalhe, de cada risada no quintal\nDos momentos em que tudo parecia especial\nCom as qualidades de ${formData.qualities || 'carinho e afeto'}\nConstruímos nossa estrada, um destino reto.`,
        lyricsStatus: 'generated'
      }));
    }
  };

  const requestLyricsAdjustment = async () => {
    if (!formData.lyricsComment.trim()) return;
    updateField('lyricsStatus', 'generating');
    try {
      const response = await fetch('/api/lyrics/improve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          currentLyrics: formData.lyrics,
          comment: formData.lyricsComment,
          formData
        })
      });

      if (response.ok) {
        const data = await response.json();
        setFormData(prev => ({
          ...prev,
          lyrics: data.lyrics,
          lyricsStatus: 'generated',
          lyricsVersion: prev.lyricsVersion + 1,
          lyricsComment: ''
        }));
      } else {
        throw new Error('Falha ao ajustar');
      }
    } catch (err) {
      console.error(err);
      updateField('lyricsStatus', 'generated');
    }
  };

  // Renderers for wizard steps
  const renderStep = () => {
    switch (step) {
      case 1:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 1: Ocasião & Homenageado</h2>
            <div style={styles.formGroup}>
              <label style={styles.label}>Qual é a ocasião especial? *</label>
              <div style={styles.grid2}>
                {occasions.map((o) => (
                  <div 
                    key={o.id}
                    onClick={() => updateField('occasion', o.id)}
                    style={{
                      ...styles.cardChoice,
                      borderColor: formData.occasion === o.id ? 'var(--primary)' : 'rgba(255,255,255,0.08)',
                      backgroundColor: formData.occasion === o.id ? 'rgba(124, 58, 237, 0.1)' : 'rgba(255,255,255,0.02)'
                    }}
                  >
                    <h4 style={{ fontSize: '1rem', marginBottom: '4px' }}>{o.label}</h4>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{o.desc}</p>
                  </div>
                ))}
              </div>
            </div>

            <div style={styles.grid2}>
              <div style={styles.formGroup}>
                <label style={styles.label}>Nome da pessoa homenageada *</label>
                <input 
                  type="text" 
                  value={formData.honoreeName} 
                  onChange={(e) => updateField('honoreeName', e.target.value)}
                  placeholder="Ex: Ana Maria, Carlos..." 
                  style={styles.input}
                />
              </div>
              <div style={styles.formGroup}>
                <label style={styles.label}>Sua relação com ela *</label>
                <input 
                  type="text" 
                  value={formData.relationship} 
                  onChange={(e) => updateField('relationship', e.target.value)}
                  placeholder="Ex: Mãe, Namorado, Esposa, Amigo..." 
                  style={styles.input}
                />
              </div>
            </div>
          </div>
        );
      case 2:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 2: Conte-nos a História</h2>
            
            <div style={styles.formGroup}>
              <label style={styles.label}>A história principal (Como se conheceram, piadas internas, trajetória) *</label>
              <textarea 
                value={formData.story} 
                onChange={(e) => updateField('story', e.target.value)}
                placeholder="Conte com detalhes. Quanto mais informações você fornecer, mais rica e fiel ficará a letra da música..."
                style={{ ...styles.input, height: '120px', resize: 'vertical' }}
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Momentos marcantes (Ex: aquela viagem especial, o pedido de namoro, etc.)</label>
              <input 
                type="text" 
                value={formData.importantMoments} 
                onChange={(e) => updateField('importantMoments', e.target.value)}
                placeholder="Ex: Viagem para Gramado em 2022, o jantar sob as estrelas..." 
                style={styles.input}
              />
            </div>

            <div style={styles.grid2}>
              <div style={styles.formGroup}>
                <label style={styles.label}>Qualidades marcantes (2 ou 3 adjetivos)</label>
                <input 
                  type="text" 
                  value={formData.qualities} 
                  onChange={(e) => updateField('qualities', e.target.value)}
                  placeholder="Ex: Alegre, batalhadora, conselheira..." 
                  style={styles.input}
                />
              </div>
              <div style={styles.formGroup}>
                <label style={styles.label}>Frase obrigatória na letra</label>
                <input 
                  type="text" 
                  value={formData.requiredPhrase} 
                  onChange={(e) => updateField('requiredPhrase', e.target.value)}
                  placeholder="Ex: Amo você até o infinito..." 
                  style={styles.input}
                />
              </div>
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>O que NÃO deve aparecer na letra (Ex: apelidos ruins, fatos tristes)</label>
              <input 
                type="text" 
                value={formData.forbiddenSubjects} 
                onChange={(e) => updateField('forbiddenSubjects', e.target.value)}
                placeholder="Ex: Não citar o antigo cachorro, não citar o acidente..." 
                style={styles.input}
              />
            </div>
          </div>
        );
      case 3:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 3: Estilo & Sonoridade</h2>
            
            <div style={styles.formGroup}>
              <label style={styles.label}>Estilo Musical desejado *</label>
              <div style={styles.grid2}>
                {stylesList.map((styleItem) => (
                  <div 
                    key={styleItem.id}
                    onClick={() => updateField('musicStyle', styleItem.id)}
                    style={{
                      ...styles.cardChoice,
                      borderColor: formData.musicStyle === styleItem.id ? 'var(--primary)' : 'rgba(255,255,255,0.08)',
                      backgroundColor: formData.musicStyle === styleItem.id ? 'rgba(124, 58, 237, 0.1)' : 'rgba(255,255,255,0.02)'
                    }}
                  >
                    <h4 style={{ fontSize: '1rem', marginBottom: '4px' }}>{styleItem.name}</h4>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{styleItem.desc}</p>
                  </div>
                ))}
              </div>
            </div>

            <div style={styles.grid3}>
              <div style={styles.formGroup}>
                <label style={styles.label}>Tipo de Voz *</label>
                <select 
                  value={formData.voiceType} 
                  onChange={(e) => updateField('voiceType', e.target.value)}
                  style={styles.select}
                >
                  <option value="">Selecione...</option>
                  <option value="feminina">Voz Feminina</option>
                  <option value="masculina">Voz Masculina</option>
                  <option value="dueto">Dueto (Feminina & Masculina)</option>
                </select>
              </div>

              <div style={styles.formGroup}>
                <label style={styles.label}>Emoção Desejada</label>
                <select 
                  value={formData.emotion} 
                  onChange={(e) => updateField('emotion', e.target.value)}
                  style={styles.select}
                >
                  <option value="">Selecione...</option>
                  <option value="emocionante">Emocionante / Romântica</option>
                  <option value="alegre">Alegre / Dançante</option>
                  <option value="nostalgica">Nostálgica / Melancólica</option>
                  <option value="divertida">Divertida / Engraçada</option>
                </select>
              </div>

              <div style={styles.formGroup}>
                <label style={styles.label}>Ritmo (Tempo)</label>
                <select 
                  value={formData.tempo} 
                  onChange={(e) => updateField('tempo', e.target.value)}
                  style={styles.select}
                >
                  <option value="">Selecione...</option>
                  <option value="lento">Lento (Acústico/Balada)</option>
                  <option value="medio">Médio (Pop/Bossa)</option>
                  <option value="rapido">Rápido (Dançante/Sertanejo)</option>
                </select>
              </div>
            </div>
          </div>
        );
      case 4:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 4: Seus Contatos</h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '24px' }}>
              Precisamos destes dados para enviar o andamento e o link final de download da música personalizada.
            </p>

            <div style={styles.formGroup}>
              <label style={styles.label}>Seu nome completo *</label>
              <input 
                type="text" 
                value={formData.customerName} 
                onChange={(e) => updateField('customerName', e.target.value)}
                placeholder="Ex: João da Silva" 
                style={styles.input}
              />
            </div>

            <div style={styles.grid2}>
              <div style={styles.formGroup}>
                <label style={styles.label}>E-mail de contato *</label>
                <input 
                  type="email" 
                  value={formData.customerEmail} 
                  onChange={(e) => updateField('customerEmail', e.target.value)}
                  placeholder="Ex: joao@email.com" 
                  style={styles.input}
                />
              </div>
              <div style={styles.formGroup}>
                <label style={styles.label}>WhatsApp de contato (com DDD) *</label>
                <input 
                  type="tel" 
                  value={formData.customerPhone} 
                  onChange={(e) => updateField('customerPhone', e.target.value)}
                  placeholder="Ex: 11999999999" 
                  style={styles.input}
                />
              </div>
            </div>

            <div style={{ ...styles.formGroup, marginTop: '16px' }}>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', cursor: 'pointer', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                <input 
                  type="checkbox" 
                  checked={formData.termsAccepted} 
                  onChange={(e) => updateField('termsAccepted', e.target.checked)}
                  style={{ marginTop: '3px' }}
                />
                <span>
                  Aceito os Termos de Uso e entendo que esta música é gerada em coprodução com Inteligência Artificial e revisada por profissionais humanos.
                </span>
              </label>
            </div>
          </div>
        );
      case 5:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 5: Composição & Revisão da Letra</h2>
            
            {formData.lyricsStatus === 'generating' ? (
              <div style={styles.generatingState}>
                <div style={styles.spinner} />
                <h3 style={{ marginTop: '16px', fontFamily: 'var(--font-family-title)' }}>Compondo versos personalizados...</h3>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '8px' }}>
                  Unindo suas memórias e transformando em melodia. Isso pode levar alguns segundos.
                </p>
              </div>
            ) : (
              <div style={styles.lyricsContainer}>
                <div style={styles.lyricsBox}>
                  <h3 style={{ fontSize: '1.2rem', marginBottom: '16px', color: 'var(--primary)' }}>Versão {formData.lyricsVersion}</h3>
                  <pre style={styles.lyricsText}>{formData.lyrics}</pre>
                </div>
                
                <div style={styles.lyricsActions}>
                  <div style={styles.formGroup}>
                    <label style={styles.label}>Gostaria de mudar algo na composição?</label>
                    <textarea 
                      value={formData.lyricsComment}
                      onChange={(e) => updateField('lyricsComment', e.target.value)}
                      placeholder="Ex: Troque o refrão para ser mais emocionante, mude o nome de x para y..."
                      style={{ ...styles.input, height: '80px' }}
                    />
                    <button 
                      onClick={requestLyricsAdjustment}
                      disabled={!formData.lyricsComment.trim()}
                      className="btn btn-secondary"
                      style={{ marginTop: '8px', width: '100%', fontSize: '0.9rem' }}
                    >
                      Solicitar Ajuste Gratuito
                    </button>
                  </div>

                  <div style={{ ...styles.infoAlert, marginTop: '16px' }} className="glass-card">
                    <p style={{ fontSize: '0.85rem', lineHeight: '1.5', color: 'var(--text-secondary)' }}>
                      💡 <strong>Dica:</strong> Se você estiver satisfeito com a letra, clique no botão "Próximo" para escolher o pacote de áudio e fechar o pedido.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        );
      case 6:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 6: Escolha o Pacote de Áudio</h2>
            <div style={styles.packagesSelectGrid}>
              {packagesList.map((pkg) => (
                <div 
                  key={pkg.id}
                  onClick={() => updateField('selectedPackage', pkg.id)}
                  style={{
                    ...styles.pkgSelectCard,
                    borderColor: formData.selectedPackage === pkg.id ? 'var(--primary)' : 'rgba(255,255,255,0.08)',
                    backgroundColor: formData.selectedPackage === pkg.id ? 'rgba(124, 58, 237, 0.1)' : 'rgba(255,255,255,0.02)'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                    <h3 style={{ fontSize: '1.25rem' }}>{pkg.name}</h3>
                    <span style={{ fontSize: '1.5rem', fontWeight: '800', color: 'var(--secondary)' }}>R$ {pkg.price.toFixed(2)}</span>
                  </div>
                  <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>{pkg.desc}</p>
                </div>
              ))}
            </div>
          </div>
        );
      case 7:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 7: Produtos Opcionais (Adicionais)</h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '24px' }}>
              Enriqueça sua homenagem com produtos extras e torne este presente ainda mais inesquecível.
            </p>

            <div style={styles.addonsList}>
              {addonsConfig.map((addon) => (
                <label key={addon.id} style={styles.addonItem} className="glass-card">
                  <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <input 
                      type="checkbox" 
                      checked={formData.addons[addon.id]}
                      onChange={(e) => updateAddon(addon.id, e.target.checked)}
                      style={styles.checkbox}
                    />
                    <div>
                      <h4 style={{ fontSize: '0.95rem', fontWeight: '600' }}>{addon.name}</h4>
                    </div>
                  </div>
                  <div style={{ fontWeight: '700', color: 'var(--secondary)' }}>
                    + R$ {addon.price.toFixed(2)}
                  </div>
                </label>
              ))}
            </div>
          </div>
        );
      case 8:
        return (
          <div style={styles.stepContent}>
            <h2 style={styles.stepHeader}>Passo 8: Resumo & Checkout</h2>
            <div style={styles.checkoutLayout}>
              <div style={styles.checkoutSummary} className="glass-card">
                <h3 style={{ fontSize: '1.2rem', marginBottom: '20px', color: 'var(--primary)' }}>Resumo do Pedido</h3>
                
                <div style={styles.summaryItem}>
                  <span>Pacote: {packagesList.find(p => p.id === formData.selectedPackage)?.name}</span>
                  <span style={{ fontWeight: '700' }}>R$ {getSelectedPackagePrice().toFixed(2)}</span>
                </div>

                {Object.keys(formData.addons).some(key => formData.addons[key]) && (
                  <div style={{ marginTop: '16px' }}>
                    <h4 style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '8px' }}>Adicionais contratados:</h4>
                    {addonsConfig.map(addon => {
                      if (formData.addons[addon.id]) {
                        return (
                          <div key={addon.id} style={{ ...styles.summaryItem, fontSize: '0.85rem', color: 'var(--text-secondary)', paddingLeft: '8px' }}>
                            <span>{addon.name}</span>
                            <span>R$ {addon.price.toFixed(2)}</span>
                          </div>
                        );
                      }
                      return null;
                    })}
                  </div>
                )}

                <hr style={{ border: 'none', borderTop: '1px solid var(--border-color)', margin: '20px 0' }} />
                
                <div style={{ ...styles.summaryItem, fontSize: '1.3rem', fontWeight: '800' }}>
                  <span>Total Geral:</span>
                  <span className="gradient-text">R$ {getTotalPrice().toFixed(2)}</span>
                </div>
              </div>

              <div style={styles.checkoutPayment}>
                <h3 style={{ fontSize: '1.2rem', marginBottom: '16px' }}>Detalhes do Faturamento</h3>
                <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: '1.6', marginBottom: '24px' }}>
                  <p><strong>Cliente:</strong> {formData.customerName}</p>
                  <p><strong>E-mail:</strong> {formData.customerEmail}</p>
                  <p><strong>WhatsApp:</strong> {formData.customerPhone}</p>
                  <p><strong>Entrega estimada:</strong> {formData.addons.priorityDelivery ? 'Até 24 horas 🚀' : 'Até 2 dias úteis'}</p>
                </div>

                <div style={styles.infoAlert} className="glass-card">
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                    🔒 Pagamento seguro processado via <strong>Mercado Pago</strong>. Suas informações estão criptografadas e protegidas.
                  </p>
                </div>

                <button 
                  onClick={async () => {
                    // Trigger Payment Integration flow
                    try {
                      const response = await fetch('/api/payments/create', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                          formData,
                          totalAmount: getTotalPrice()
                        })
                      });
                      if (response.ok) {
                        const data = await response.json();
                        if (data.init_point) {
                          window.location.href = data.init_point; // Redirect to Mercado Pago checkout
                        } else {
                          alert('Erro ao redirecionar para pagamento. Usando modo simulação.');
                          window.location.href = `/acompanhar?id=MOCK-ORDER-12345`;
                        }
                      } else {
                        throw new Error('Falha no pagamento');
                      }
                    } catch (err) {
                      console.error(err);
                      alert('Redirecionando para fluxo simulado de confirmação de pedido.');
                      window.location.href = `/acompanhar?id=MOCK-ORDER-12345`;
                    }
                  }}
                  className="btn btn-primary"
                  style={{ width: '100%', padding: '16px', fontSize: '1.1rem', marginTop: '24px' }}
                >
                  Ir para o Pagamento Seguro 💳
                </button>
              </div>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  const isNextDisabled = () => {
    if (step === 1 && (!formData.occasion || !formData.honoreeName || !formData.relationship)) return true;
    if (step === 2 && !formData.story) return true;
    if (step === 3 && (!formData.musicStyle || !formData.voiceType)) return true;
    if (step === 4 && (!formData.customerName || !formData.customerEmail || !formData.customerPhone || !formData.termsAccepted)) return true;
    if (step === 5 && formData.lyricsStatus !== 'generated') return true;
    if (step === 6 && !formData.selectedPackage) return true;
    return false;
  };

  return (
    <div style={styles.wrapper}>
      {/* Header */}
      <header style={styles.header} className="glass-panel">
        <div style={styles.headerContainer}>
          <Link href="/" style={styles.logo}>
            <span style={styles.logoIcon}>🎵</span>
            <span style={styles.logoText}>NS<span className="gradient-text">Nexus</span></span>
          </Link>
          <div style={styles.stepIndicator}>
            Passo {step} de {totalSteps}
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main style={{ flex: 1, padding: '40px 0' }}>
        <div className="container" style={{ maxWidth: '900px' }}>
          {/* Progress bar */}
          <div style={styles.progressBarBg}>
            <div style={{ ...styles.progressBarFill, width: `${(step / totalSteps) * 100}%` }} />
          </div>

          {/* Render Active Step */}
          <div style={{ marginTop: '32px' }}>
            {renderStep()}
          </div>

          {/* Navigation Controls */}
          <div style={styles.navigationControls}>
            {step > 1 && (
              <button onClick={prevStep} className="btn btn-secondary" style={{ padding: '12px 24px' }}>
                ← Voltar
              </button>
            )}
            {step < totalSteps ? (
              <button 
                onClick={nextStep} 
                disabled={isNextDisabled()} 
                className="btn btn-primary" 
                style={{ padding: '12px 32px', marginLeft: 'auto' }}
              >
                Próximo passo →
              </button>
            ) : null}
          </div>
        </div>
      </main>
    </div>
  );
}

const styles = {
  wrapper: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#0a0a0c',
  },
  header: {
    borderRadius: 0,
    borderTop: 'none',
    borderLeft: 'none',
    borderRight: 'none',
  },
  headerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '16px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  logoIcon: {
    fontSize: '1.5rem',
  },
  logoText: {
    fontFamily: 'var(--font-family-title)',
    fontWeight: '800',
    fontSize: '1.3rem',
    letterSpacing: '-0.02em',
    color: '#fff',
  },
  stepIndicator: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: 'var(--text-secondary)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    padding: '6px 14px',
    borderRadius: '100px',
    border: '1px solid var(--border-color)',
  },
  progressBarBg: {
    width: '100%',
    height: '6px',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: '100px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    background: 'linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%)',
    transition: 'width 0.3s ease',
  },
  stepContent: {
    animation: 'fadeIn 0.4s ease',
  },
  stepHeader: {
    fontSize: '1.8rem',
    marginBottom: '32px',
    fontFamily: 'var(--font-family-title)',
  },
  formGroup: {
    marginBottom: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
  },
  input: {
    width: '100%',
    padding: '14px 18px',
    backgroundColor: 'rgba(255,255,255,0.03)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: '#fff',
    fontFamily: 'var(--font-family-body)',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.2s',
    ':focus': {
      borderColor: 'var(--primary)',
    },
  },
  select: {
    width: '100%',
    padding: '14px 18px',
    backgroundColor: '#121216',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: '#fff',
    fontFamily: 'var(--font-family-body)',
    fontSize: '1rem',
    outline: 'none',
    cursor: 'pointer',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '20px',
    marginBottom: '16px',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '20px',
  },
  cardChoice: {
    padding: '20px',
    borderRadius: 'var(--border-radius-sm)',
    border: '1px solid',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  navigationControls: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '40px',
    borderTop: '1px solid var(--border-color)',
    paddingTop: '24px',
  },
  generatingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    textAlign: 'center',
  },
  spinner: {
    width: '50px',
    height: '50px',
    border: '4px solid rgba(255,255,255,0.06)',
    borderTopColor: 'var(--primary)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  lyricsContainer: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 0.8fr',
    gap: '32px',
    '@media (max-width: 768px)': {
      gridTemplateColumns: '1fr',
    },
  },
  lyricsBox: {
    backgroundColor: 'rgba(255,255,255,0.02)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    padding: '32px',
  },
  lyricsText: {
    fontFamily: 'var(--font-family-body)',
    fontSize: '1.05rem',
    lineHeight: '1.7',
    color: '#fff',
    whiteSpace: 'pre-wrap',
  },
  lyricsActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  infoAlert: {
    padding: '16px 20px',
    borderRadius: 'var(--border-radius-sm)',
    border: '1px solid rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.01)',
  },
  packagesSelectGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  pkgSelectCard: {
    padding: '24px 32px',
    borderRadius: 'var(--border-radius-md)',
    border: '1px solid',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  addonsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  addonItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    cursor: 'pointer',
    border: '1px solid rgba(255,255,255,0.06)',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  },
  checkoutLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '40px',
    '@media (max-width: 768px)': {
      gridTemplateColumns: '1fr',
    },
  },
  checkoutSummary: {
    padding: '32px',
  },
  summaryItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
    fontSize: '0.95rem',
  },
  checkoutPayment: {
    display: 'flex',
    flexDirection: 'column',
  },
};
