// Estilos do wizard de /criar — extraído de page.jsx (M-20 no AUDIT_REPORT.md) para reduzir o
// tamanho do arquivo principal. Objeto 100% estático (sem closures sobre estado do componente).
export const styles = {
  wrapper: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'var(--bg-primary)',
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 100,
    borderRadius: 0,
    borderWidth: '0 0 1px 0',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  headerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '12px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stepIndicator: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: 'var(--primary)',
    backgroundColor: 'var(--primary-light)',
    padding: '6px 14px',
    borderRadius: '100px',
    border: '1px solid rgba(124, 58, 237, 0.2)',
  },
  progressBarBg: {
    width: '100%',
    height: '6px',
    backgroundColor: 'var(--border-color)',
    borderRadius: '100px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    background: 'linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%)',
    transition: 'width 0.3s ease',
  },
  stepTitle: {
    fontSize: '1.8rem',
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: '8px',
    fontFamily: 'var(--font-family-title)',
    color: 'var(--text-primary)',
  },
  stepSubtitle: {
    fontSize: '0.98rem',
    textAlign: 'center',
    color: 'var(--text-muted)',
    marginBottom: '28px',
  },
  gridCards: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))',
    gap: '14px',
    marginTop: '16px',
  },
  gridCards2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '16px',
    marginTop: '16px',
  },
  wizardCard: {
    aspectRatio: '1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    userSelect: 'none',
    backgroundColor: '#FFFFFF',
    boxShadow: 'var(--card-shadow)',
  },
  wizardCardLarge: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    userSelect: 'none',
    backgroundColor: '#FFFFFF',
    boxShadow: 'var(--card-shadow)',
  },
  checkCircle: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: 'var(--primary)',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.82rem',
    fontWeight: 'bold',
    boxShadow: '0 2px 8px rgba(124, 58, 237, 0.4)',
  },
  wizardInput: {
    width: '100%',
    padding: '16px 20px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-family-body)',
    fontSize: '1.1rem',
    outline: 'none',
    transition: 'all 0.2s',
    marginTop: '16px',
    textAlign: 'center',
    boxShadow: '0 2px 6px rgba(0,0,0,0.02)',
  },
  wizardLabel: {
    fontSize: '0.95rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    marginBottom: '8px',
    display: 'block',
  },
  wizardTextarea: {
    width: '100%',
    padding: '16px 20px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-family-body)',
    fontSize: '1rem',
    outline: 'none',
    transition: 'all 0.2s',
    resize: 'vertical',
    boxShadow: '0 2px 6px rgba(0,0,0,0.02)',
  },
  wizardListBtn: {
    width: '100%',
    padding: '16px',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: 'var(--text-primary)',
    backgroundColor: '#FFFFFF',
    fontSize: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'center',
  },
  wizardPillBtn: {
    padding: '14px 28px',
    borderRadius: '100px',
    border: '1.5px solid var(--border-color)',
    backgroundColor: '#FFFFFF',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '700',
    transition: 'all 0.2s',
  },
  voiceBtn: {
    flex: 1,
    padding: '16px',
    borderRadius: 'var(--border-radius-sm)',
    color: 'var(--text-primary)',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    fontSize: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.25s',
  },
  navigationControls: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    borderTop: '1.5px solid var(--border-color)',
    boxShadow: '0 -4px 20px rgba(0, 0, 0, 0.06)',
    padding: '12px 16px',
  },
  checkoutSummary: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    backgroundColor: '#FFFFFF',
    borderRadius: 'var(--border-radius-md)',
  },
  summaryItemRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.95rem',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '8px',
  },
  summaryItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.95rem',
  },
  infoAlert: {
    padding: '16px 20px',
    borderRadius: 'var(--border-radius-sm)',
    border: '1px solid var(--border-color)',
    backgroundColor: 'var(--bg-secondary)',
  },
  generatingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    textAlign: 'center',
  },
  spinner: {
    width: '50px',
    height: '50px',
    border: '4px solid var(--border-color)',
    borderTopColor: 'var(--primary)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  lyricsBox: {
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    padding: '24px',
    boxShadow: 'var(--card-shadow)',
  },
  lyricsText: {
    fontFamily: 'var(--font-family-body)',
    fontSize: '1rem',
    lineHeight: '1.75',
    color: 'var(--text-primary)',
    whiteSpace: 'pre-wrap',
  },
  lyricsActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  packagesSelectGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    maxWidth: '700px',
    margin: '24px auto 0',
  },
  pkgSelectCard: {
    padding: '20px 24px',
    borderRadius: 'var(--border-radius-md)',
    border: '1.5px solid var(--border-color)',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    transition: 'all 0.25s',
    boxShadow: 'var(--card-shadow)',
  },
  addonsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    maxWidth: '700px',
    margin: '24px auto 0',
  },
  addonItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    cursor: 'pointer',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    backgroundColor: '#FFFFFF',
  },
  checkbox: {
    width: '20px',
    height: '20px',
    cursor: 'pointer',
    accentColor: 'var(--primary)',
  },
};
