// Estilos de /entrega — extraído de page.jsx (M-20 no AUDIT_REPORT.md) para reduzir o tamanho do
// arquivo principal. Objeto 100% estático (sem closures sobre estado do componente).
export const styles = {
  wrapper: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'var(--bg-primary)',
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 100,
    borderRadius: 0,
    borderWidth: '0 0 1px 0',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  headerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '12px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusBadge: {
    fontSize: '0.85rem',
    fontWeight: '700',
    padding: '6px 14px',
    borderRadius: '100px',
    border: '1px solid',
  },
  deliveryCard: {
    padding: '28px',
    marginBottom: '28px',
    backgroundColor: '#FFFFFF',
    boxShadow: 'var(--card-shadow)',
  },
  mediaSide: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  coverWrapper: {
    position: 'relative',
    borderRadius: 'var(--border-radius-md)',
    overflow: 'hidden',
    aspectRatio: '1',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.12)',
  },
  coverImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  coverOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    background: 'linear-gradient(to top, rgba(15, 23, 42, 0.9) 0%, rgba(15, 23, 42, 0.3) 60%, transparent 100%)',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    color: '#FFFFFF',
  },
  audioPlayerContainer: {
    padding: '18px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    boxShadow: 'var(--card-shadow)',
  },
  audioTag: {
    width: '100%',
    height: '40px',
    outline: 'none',
  },
  downloadGrid: {
    display: 'flex',
    gap: '12px',
  },
  downloadBtn: {
    flex: 1,
    padding: '12px',
    textAlign: 'center',
    fontSize: '0.9rem',
    textDecoration: 'none'
  },
  qrCard: {
    padding: '18px',
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
  },
  qrImg: {
    width: '100px',
    height: '100px',
    borderRadius: 'var(--border-radius-sm)',
    border: '3px solid #FFFFFF',
    boxShadow: '0 4px 10px rgba(0,0,0,0.08)',
  },
  lyricsSide: {
    padding: '28px',
    maxHeight: '620px',
    overflowY: 'auto',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-md)',
    boxShadow: 'var(--card-shadow)',
  },
  lyricsText: {
    fontFamily: 'var(--font-family-body)',
    fontSize: '1rem',
    lineHeight: '1.8',
    color: 'var(--text-primary)',
    whiteSpace: 'pre-wrap',
  },
  blockedCard: {
    padding: '36px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid var(--warning)',
    backgroundColor: 'var(--warning-bg)',
    borderRadius: 'var(--border-radius-md)',
  },
  feedbackCard: {
    padding: '28px',
    backgroundColor: '#FFFFFF',
    boxShadow: 'var(--card-shadow)',
  },
  reviewForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  starsContainer: {
    display: 'flex',
    gap: '8px',
  },
  starBtn: {
    background: 'none',
    border: 'none',
    fontSize: '2rem',
    cursor: 'pointer',
    padding: 0,
    outline: 'none',
    transition: 'color 0.1s',
  },
  reviewTextarea: {
    width: '100%',
    height: '100px',
    padding: '14px 18px',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid var(--border-color)',
    borderRadius: 'var(--border-radius-sm)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-family-body)',
    fontSize: '0.95rem',
    outline: 'none',
    resize: 'vertical',
  },
  reviewSuccess: {
    textAlign: 'center',
    padding: '20px 0',
  },
  spinner: {
    width: '44px',
    height: '44px',
    border: '3px solid var(--border-color)',
    borderTopColor: 'var(--primary)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
};
